// export const metadata={
//   title:"About nextjs",
//   description:"nextjs is framework of react"

// }
import type { Metadata } from 'next'

export const metadata: Metadata={
  title:{
    default:"Next.js Tutorial - Codevaolution",
    template:"%s | codevolution",
    // absolute:,
  },
  description:"Generated by next.js"
}
export default function About() {
  return (
    <h1>About page</h1>
  );
}
