import {Metadata} from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata:Metadata={
  title:{
    default:"Next.js Tutorial- Codevolution",
    template:"%s | codevolution",
  },
  description:"Generated by Next.js",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="">
        <header style={{backgroundColor:"lightblue",padding:"1rem"}}>
          <p>Header</p>
        </header>
        
        <ErrorWrapper>
        {children}
        </ErrorWrapper>
        
        <footer style={{backgroundColor:"ghostwhite",padding:"1rem"}}>
          {/* <p>Footer</p> */}
        </footer>
        </body>
        
    </html>
  );
}
